sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: ${ALIBABA_ACCESS_KEY_ID} #防止push是git扫描不通过，改为springboot的environment variables
    accessKeySecret: ${ALIBABA_ACCESS_KEY_SECRET}
    bucket-name: ocean-bucket-01